version: '3' 
services: 
  web: 
    build: . 
    ports: 
      - "5000:5000" 
    volumes: 
      - .:/app 
    environment: 
      - FLASK_ENV=development 
  mysql: 
    image: mysql:latest 
    container_name: mysql-container 
    environment: 
      MYSQL_ROOT_PASSWORD: Beaulieu25082024 
      MYSQL_DATABASE: TradeAlgoDB 
    ports: 
      - "3306:3306" 
    volumes: 
      - mysql-data:/var/lib/mysql 
volumes: 
  mysql-data: {} 
