version: '3' 
services: 
  web: 
    build: . 
    ports: 
      - "5000:5000" 
    volumes: 
      - .:/app 
    environment: 
      - FLASK_ENV=development 
  blockchain: 
    build: 
      context: ./blockchain 
    ports: 
      - "8545:8545" 
    volumes: 
      - ./blockchain:/app 
