
# deploy.yml
name: Deploy Contracts

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Blockchain Contracts
        run: python scripts/deploy_contracts.py
